# This is a basic workflow to help you get started with Actions

name: deploy-cloud-function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy-Hello-World:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gcloud SDK environment
        uses: google-github-actions/setups-gcloud@v0
        with: 
          service_account_email: "tu.tran@nganhanhmedia.com"
          service_account_key: "7c3338894376fd81619ef1aa7a159fc9c627d99e"
          project_id: "synthetic-cargo-314006"
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Deploy the function
        run: gcloud functions deploy test-hello-world --trigger-http --runtime=python39
