# This is a basic workflow to help you get started with Actions

name: deploy-cloud-function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy-Hello-World:
    runs-on: ubuntu-latest
    
    steps:
    # Google Cloud server authentication with credentials_json key generated
      - id: 'auth'
        name: 'Authenticate to Google Cloud Server'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{secrets.google_map_sa_key}}'
    # Setup Google Clous sdk environment for the task
      - id: 'setup'
        name: 'Setup Gcloud SDK environment'
        uses: 'google-github-actions/setup-gcloud@v0.2.1'
    # Test Gcloud info
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    # Deploy the test function to Google Cloud Functions
      - id: 'deploy'
        name: 'Deploy test helo world the function'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'test-hello-world'
          runtime: 'python39'
    # Test output after deployed function
      - name: 'Test cloud function output'
        run: 'curl "${{steps.deploy.outputs.url}}"'
